const templateGrafts = {
  grafts: [
    'Aerial (CR 1+)',
    'Aqueous (CR 1+)',
    'Astral',
    'Celestial',
    'Cthonic (CR 1+)',
    'Cybernetic (CR 1/2+)',
    'Entropic',
    'Fiendish',
    'Fiery (CR 1+)',
    'Giant (CR 1+)',
    'Miniature',
    'Phrenic',
    'Resolute',
    'Synthetic',
    'Two-Headed (CR 3+)',
    'Umbral',
  ],

  'Aerial (CR 1+)': {
    'description': 'Aerial creatures are native denizens of the Elemental Plane of\n' +
        '  Air, gas giant planets, or similar landless environments, and\n' +
        '  have unique adaptations to help them survive there.',
    'trait': [],
    'adjustment': [{'npcSenses': 'Darkvision 60 ft. '}],
  },
  'Aqueous (CR 1+)': {'description': '', 'train': [], 'adjustment': []},
  'Astral': {'description': '', 'train': [], 'adjustment': []},
  'Celestial': {'description': '', 'train': [], 'adjustment': []},
  'Cthonic (CR 1+)': {'description': '', 'train': [], 'adjustment': []},
  'Cybernetic (CR 1/2+)': {'description': '', 'train': [], 'adjustment': []},
  'Entropic': {'description': '', 'train': [], 'adjustment': []},
  'Fiendish': {'description': '', 'train': [], 'adjustment': []},
  'Fiery (CR 1+)': {'description': '', 'train': [], 'adjustment': []},
  'Giant (CR 1+)': {'description': '', 'train': [], 'adjustment': []},
  'Miniature': {'description': '', 'train': [], 'adjustment': []},
  'Phrenic': {'description': '', 'train': [], 'adjustment': []},
  'Resolute': {'description': '', 'train': [], 'adjustment': []},
  'Synthetic': {'description': '', 'train': [], 'adjustment': []},
  'Two-Headed (CR 3+)': {'description': '', 'train': [], 'adjustment': []},
  'Umbral': {'description': '', 'train': [], 'adjustment': []},
};