const npcGrafts = {
  grafts : [
 //   '--Elemental--',
    'Air',
    'Earth',
    'Fire',
    'Ice',
    'Lightning',
    'Magma',
    'Water',
  //  '--Environmental--',
    'Airborne',
    'Aquatic',
    'Arboreal',
    'Arctic',
    'Desert',
    'Forest',
    'Marsh',
    'Mountain',
    'Plains',
    'Radioactive',
    'Solar',
    'Space',
    'Subterranean',
    'Thermic',
  //  '--Template--',
    'Aerial (CR 1+)',
    'Aqueous (CR 1+)',
    'Astral',
    'Celestial',
    'Cthonic (CR 1+)',
    'Cybernetic (CR 1/2+)',
    'Entropic',
    'Fiendish',
    'Fiery (CR 1+)',
    'Giant (CR 1+)',
    'Miniature',
    'Phrenic',
    'Resolute',
    'Synthetic',
    'Two-Headed (CR 3+)',
    'Umbral',
    //'--Occult--',
    'Obscured',
    'Nightmare',
    'Transposed']
}