const menuData = {
  subtypes: [
    "Aanung-an",
    "Aeon",
    "Agathion",
    "Air",
    "Android",
    "Angel",
    "Aquatic",
    "Archon",
    "Azata",
    "Brenneri",
    "Cold",
    "Daemon",
    "Damai",
    "Demon",
    "Dessamar",
    "Devil",
    "Dirindi",
    "Dwarf",
    "Earth",
    "Elemental",
    "Elf",
    "Espraksa",
    "Extraplanar",
    "Fire",
    "Giant",
    "Gnome",
    "Goblinoid",
    "Gray",
    "Halfling",
    "Human",
    "Ikeshti",
    "Incorporeal",
    "Inevitable",
    "Kami",
    "Kasatha",
    "Khizar",
    "Lashunta",
    "Maraquoi",
    "Mindscape",
    "Native",
    "Oni",
    "Orc",
    "Pahtra",
    "Phentomite",
    "Plantlike",
    "Protean",
    "Pyric Revenant",
    "Pyric Wraith",
    "Reptoid",
    "Reptoid Hybrid",
    "Ryphorian",
    "Sarcesian",
    "Shakalta",
    "Shapechanger",
    "Shatori",
    "Shimreen",
    "Shirren",
    "Skittermander",
    "Spectra",
    "Strix",
    "Velstrac",
    "Verthani",
    "Vesk",
    "Vlaka",
    "Water",
    "Ysoki",

    "Anunnaki",
    "Deoxyomorphic",
    "Great Old One",
    "Kitsune",
    "Kumiho",
    "Levialogos",
    "Soulless",
    "Soulshell",
    "Uramae"
  ],
  classes: [
    "Envoy",
    "Mechanic",
    "Mystic",
    "Operative",
    "Solarian",
    "Soldier",
    "Technomancer",
    "Elementian"],
  species: [
    "N/A",
    "Android",
    "Brenneri",
    "Damai",
    "Dessamar",
    "Dirindi",
    "Dwarf",
    "Drow",
    "Elf",
    "Gnome",
    "Gray",
    "Half-Elf",
    "Halfing",
    "Hobgoblin",
    "Human",
    "Ikeshti",
    "Kanobo",
    "Kasatha",
    "Khizar",
    "Lashunta",
    "Maraquoi",
    "Orc",
    "Pathra",
    "Phentomite",
    "Reptoid",
    "Ryphorian",
    "Sarcesian",
    "Shakalta",
    "Shatori",
    "Shimreen",
    "Shirren",
    "Skittermander",
    "Strix",
    "Verthani",
    "Vesk",
    "Vlaka",
    "Ysoki"
  ],
  templateGrafts: [
    "Aerial (CR 1+)",
    "Aqueous (CR 1+)",
    "Astral",
    "Celestial",
    "Cthonic (CR 1+)",
    "Cybernetic (CR 1/2+)",
    "Entropic",
    "Fiendish",
    "Fiery (CR 1+)",
    "Giant (CR 1+)",
    "Miniature",
    "Phrenic",
    "Resolute",
    "Synthetic",
    "Two-Headed (CR 3+)",
    "Umbral"
  ],
  summoningGraftList: [
    "Aeon",
    "Agathion",
    "Angel",
    "Archon",
    "Azata",
    "Daemon",
    "Demon",
    "Devil",
    "First World Beast",
    "Inevitable",
    "Protean",
    "Robot",
    "Shadow Creature"
  ],
  envGrafts: [
    "Airborne",
    "Aquatic",
    "Arboreal",
    "Arctic",
    "Desert",
    "Forest",
    "Marsh",
    "Mountain",
    "Plains",
    "Radioactive",
    "Solar",
    "Space",
    "Subterranean",
    "Thermic"
  ],
  occultGrafts: [
    "Obscured",
    "Nightmare",
    "Transposed"],
  sizes: [
    "Ultrafine",
    "Fine",
    "Dimunitive",
    "Tiny",
    "Small",
    "Medium",
    "Large",
    "Huge",
    "Gargantuan",
    "Colossal",
    "Supercolossal"],
  typeList: [
    "Aberration",
    "Animal",
    "Construct",
    "Dragon",
    "Fey",
    "Humanoid",
    "Magical Beast",
    "Monstrous Humanoid",
    "Ooze",
    "Outsider",
    "Plant",
    "Undead",
    "Vermin"],
  otherGrafts: [
    "Aasimar (Planar Scion)",
    "Abysium Dragon (Dragon (Starmetal))",
    "Adamantine Dragon (Dragon (Starmetal))",
    "Air Elemental (Elemental)",
    "Air Mephit (Mephit)",
    "Air Wysp (Wysp)",
    "Airborne (Environmental)",
    "Animated Armor",
    "Aquatic (Environmental)",
    "Arboreal (Environmental)",
    "Arctic (Environmental)",
    "Baykok",
    "Black Dragon (Dragon (Chromatic))",
    "Blue Dragon (Dragon (Chromatic))",
    "Bone Trooper",
    "Brass Dragon (Dragon (Metallic))",
    "Bronze Dragon (Dragon (Metallic))",
    "Carrion Dreg",
    "Cloud Giant (Giant)",
    "Colour-Blighted (Colour out of Space)",
    "Copper Dragon (Dragon (Metallic))",
    "Corpsefolk",
    "Cybernetic Zombie (Undead Minion)",
    "Damoritoshs Arm (Symbiend)",
    "Desert (Environmental)",
    "Dream Peddler (Symbiend)",
    "Driftdead (Driftdead)",
    "Driftdead",
    "Driftdead Amalgam (Driftdead)",
    "Dust Mephit (Mephit)",
    "Dycepskian-Infested (Dycepskian)",
    "Earth Elemental (Elemental)",
    "Earth Mephit (Mephit)",
    "Earth Wysp (Wysp)",
    "Eclipse Giant (Giant)",
    "Emotivore",
    "Exsiccate (Exsiccate)",
    "Fire Elemental (Elemental)",
    "Fire Giant (Giant)",
    "Fire Mephit (Mephit)",
    "Fire Wysp (Wysp)",
    "Flayer Leech Efigy",
    "Forest (Environmental)",
    "Gatecrasher",
    "Genesis Wraith",
    "Ghast (Ghoul)",
    "Ghost",
    "Ghoul (Ghoul)",
    "Giant (Creautre Subtype)",
    "Gold Dragon (Dragon (Metallic))",
    "Green Dragon (Dragon (Chromatic))",
    "Horacalcum Dragon (Dragon (Starmetal))",
    "Ice Elemental (Elemental)",
    "Ice Mephit (Mephit)",
    "Ifrit (Planar Scion)",
    "Jiang-Shi (Vampire)",
    "Kurobozu",
    "Lacedon (Ghoul)",
    "Lightning Elemental (Elemental)",
    "Lunar Dragon (Dragon (Outer))",
    "Magma Elemental (Elemental)",
    "Marooned One",
    "Marrowblight",
    "Marsh (Environmental)",
    "Mind-Swapped",
    "Mohrg",
    "Moon Giant (Giant)",
    "Mountain (Environmental)",
    "Necrovite",
    "Nihili",
    "Noqual Dragon (Dragon (Starmetal))",
    "Oblivion Shade",
    "Occult Zombie (Undead Minion)",
    "Oread (Planar Scion)",
    "Pale Stranger",
    "Paragon (Symbiend)",
    "Plains (Environmental)",
    "Pollution Mephit (Mephit)",
    "Radiation Mephit (Mephit)",
    "Radioactive (Environmental)",
    "Rebuilt",
    "Red Dragon (Dragon (Chromatic))",
    "Shadow-Marred",
    "Siccatite Dragon (Dragon (Starmetal))",
    "Silver Dragon (Dragon (Metallic))",
    "Skeletal Undead (Undead Minion)",
    "Slag Giant (Giant)",
    "Solar (Environmental)",
    "Solar Dragon (Dragon (Outer))",
    "Songtwisted",
    "Space (Environmental)",
    "Steam Mephit (Mephit)",
    "Stone Giant (Giant)",
    "Storm Giant (Giant)",
    "Subterranean (Environmental)",
    "Suli (Planar Scion)",
    "Sun Giant (Giant)",
    "Sylph (Planar Scion)",
    "Tech Mephit (Mephit)",
    "Thermic (Environmental)",
    "Tiefling (Planar Scion)",
    "Time Dragon (Dragon (Outer))",
    "Tsukumogami",
    "Undine (Planar Scion)",
    "Varthorian",
    "Void Dragon (Dragon (Outer))",
    "Void Zombie",
    "Vortex Dragon (Dragon (Outer))",
    "Vorthuul",
    "Water Elemental (Elemental)",
    "Water Mephit (Mephit)",
    "Water Wysp (Wysp)",
    "White Dragon (Dragon (Chromatic))"
  ],
  elementalGrafts: [
    "Air",
    "Earth",
    "Fire",
    "Ice",
    "Lightning",
    "Magma",
    "Water"
  ],
};