const npcSubTypes = {
  subtypes: [
    'Aanung-an',
    'Aeon',
    'Agathion',
    'Air',
    'Android',
    'Angel',
    'Aquatic',
    'Archon',
    'Azata',
    'Brenneri',
    'Cold',
    'Daemon',
    'Damai',
    'Demon',
    'Dessamar',
    'Devil',
    'Dirindi',
    'Dwarf',
    'Earth',
    'Elemental',
    'Elf',
    'Espraksa',
    'Extraplanar',
    'Fire',
    'Giant',
    'Gnome',
    'Goblinoid',
    'Gray',
    'Halfling',
    'Human',
    'Ikeshti',
    'Incorporeal',
    'Inevitable',
    'Kami',
    'Kasatha',
    'Khizar',
    'Lashunta',
    'Maraquoi',
    'Mindscape',
    'Native',
    'Oni',
    'Orc',
    'Pahtra',
    'Phentomite',
    'Plantlike',
    'Protean',
    'Pyric Revenant',
    'Pyric Wraith',
    'Reptoid',
    'Reptoid Hybrid',
    'Ryphorian',
    'Sarcesian',
    'Shakalta',
    'Shapechanger',
    'Shatori',
    'Shimreen',
    'Shirren',
    'Skittermander',
    'Spectra',
    'Strix',
    'Swarm',
    'Troop',
    'Velstrac',
    'Verthani',
    'Vesk',
    'Vlaka',
    'Water',
    'Ysoki',

    'Anunnaki',
    'Deoxyomorphic',
    'Great Old One',
    'Kitsune',
    'Kumiho',
    'Levialogos',
    'Soulless',
    'Soulshell',
    'Uramae',
  ],

  'Aeon': {
    'description': 'Aeons are a race of neutral outsiders who maintain the balance of reality.',
    'reference': 'Alien Archive 2 pg. 136, Alien Archive pg. 133',
    'trait': [], 'adjustment': [
      {'npcImmunities': 'Immunity to cold, critical hits, and poison; '},
      {'npcResistances': 'Resistance 10 to electricity and fire; '}],
    'specials': [
      {'npcSpecialsTemp': {'Envisaging (Su)': 'Aeons communicate without language, first scanning beings for their thoughts and intentions and then projecting psychic flashes of a single concept in response. These flashes are usually a combination of visual and aural stimulation that communicate the aeon’s intent or understanding. An aeon’s envisaging functions as a nonverbal form of telepathy with a range of 100 feet, and it counts as a language for the purposes of telepathy and truespeech. Aeons can’t read the thoughts of creatures immune to mind-affecting effects.'}},
      {'npcSpecialsTemp': {'Extension of All (Ex)': 'Aeons can communicate telepathically with other aeons over vast distances. This ability works even across planes, albeit less effectively, allowing the communication of only vague impressions and feelings.'}},
    ],
  },
  'Aanung-an': {
    'description': 'Any creature that dies while performing dark rituals for evil purposes risks rising again as one of the occult dead. (Required Creature Type: Undead. Suggested Array: Spellcaster. Suggested Ability Scores: Intelligence, Wisdom, Charisma. Mysticism as a master skill)',
    'specials': [
      {'npcSpecialsTemp': {'Ritual Scar (Su)': 'An aanung-an that starts its turn grappling a creature can attempt to carve a ritual scar into its victim’s body as a standard action, afflicting it with potent magic. The aanung-an attempts a Mysticism check (DC = 20 + target’s level or CR). On a success, the aanung-an renews the grapple, and the target takes 1d6+4 slashing damage as the aanung-an claws a symbol into its body. The target must then succeed at a DC 15 Will saving throw or suffer one of the following effects of the aanung-an’s choice: bestow curse, slow, or suggestion. These effects function at the aanung-an’s caster level. Certain aanung-ans might inflict different or unique effects with this ability, at the GM’s discretion.'}},
    ],
    'reference': 'Starfinder #25: The Chimera Mystery pg. 55',
    'trait': [],
    'adjustment': [
      {'npcSenses': 'Blindsense (thought) 30 ft.; '},
    ],
  },
  'Agathion': {
    'description': 'Agathions are celestials, or good outsiders, native to Nirvana.',
    'trait': [],
    'reference': 'Alien Archive pg. 134',
    'adjustment': [
      {'npcSenses': 'Low-light vision; '},
      {'npcSaveBonus': '+4 to saving throws against poison; '},
      {'npcImmunities': 'electricity; petrification; '},
      {'npcResistances': 'resistance 10 to cold and sonic; '},
      {'npcOtherAbilities': 'healing channel (as per the healer mystic connection power); truespeech; speak with animals (as per the xenodruid mystic connection power); '}],
  },
  'Air': {
    'description': 'This subtype is usually applied to outsiders with a connection to the Plane of Air.',
    'reference': 'Alien Archive pg. 134',
    'trait': [],
    'adjustment': [{'npcOtherAbilities': 'Flight (Perfect Maneuverability); '}],
    'masterSkills': ['npcAthl'], // or good
  },
  'Android': {
    'description': 'This subtype is applied to androids and creatures related to androids.(if the NPC is of the android race, it also gains the constructed, flat affect, and upgrade slot racial traits.)',
    'reference': 'Alien Archive pg. 134',
    'trait': [],
    'adjustment': [{'npcSenses': 'Low-light vision; Darkvision 60 ft.; '}],
  },
  'Angel': {
    'description': 'Angels are celestials, or good outsiders, native to the good-aligned Outer Planes.',
    'trait': [],
    'reference': 'Alien Archive pg. 134',
    'adjustment': [
      {'npcSenses': 'Low-light vision; Darkvision 60 ft.; '},
      {'npcImmunities': 'immunity to acid, cold, and petrification; '},
      {'npcResistances': 'resistance 10 to electricity and fire; '},
      {'npcOtherAbilities': 'truespeech; '},
      {'npcSaveBonus': ' +4 to saving throws against poison; '},
    ],
    'specials': [
      {'npcSpecialsTemp': {'Protective Aura (Su)': 'For angels of CR 3 to CR 15, this ability grants creatures within the aura (usually 20 feet), including the angel, a divine bonus (usually +2) to AC against attacks made by evil creatures and a divine bonus (usually +4) to saving throws against effects created by evil creatures. The protective aura of a more powerful or a weaker angel might grant a larger or smaller bonus and have a larger or smaller radius, respectively.'}}],
  },
  'Aquatic': {
    'description': 'These creatures are often native to environments that are mostly or entirely underwater. (if it can breathe air, it also gains the amphibious universal creature rule.)',
    'trait': [],
    'reference': 'Alien Archive 3 pg. 148, Alien Archive pg. 134',
    'adjustment': [],
    'masterSkills': ['npcAthl'], // or good
  },
  'Archon': {
    'description': 'Archons are celestials, or good outsiders, native to Heaven. ( many archons can cast teleport as an at-will spell-like ability (caster level equal to its CR))',
    'trait': [],
    'reference': 'Alien Archive pg. 134',
    'adjustment': [
      {'npcSenses': 'Low-light vision; Darkvision 60 ft.; '},
      {'npcSaveBonus': '+4 to saving throws against poison; '},
      {'npcImmunities': 'immunity to electricity and petrification; '},
      {'npcResistances': 'resistance 10 to cold and fire; '},
      {'npcOtherAbilities': 'truespeech; '}],
    'specials': [
      {'npcSpecialsTemp': {'Aura of Menace (Su)': 'This ability imposes a divine penalty (usually –2) to the AC, attacks, and saving throws of each hostile creature within the aura (usually 20 feet) that fails a Will save. This penalty lasts for 24 hours or until that creature deals damage to the archon who generated the aura. A creature that has resisted or broken the effect can’t be affected again by the same archon’s aura for 24 hours. The aura of a more powerful or weaker archon might impose a larger or smaller penalty and might have a larger or smaller radius, respectively.'}}],
  },
  'Azata': {
    'description': 'Azatas are celestials, or good outsiders, native to Elysium.',
    'trait': [],
    'reference': 'Alien Archive 2 pg. 136, Alien Archive pg. 134',
    'adjustment': [
      {'npcSenses': 'Low-light vision; Darkvision 60 ft.; '},
      {'npcImmunities': 'immunity to electricity and petrification; '},
      {'npcOtherAbilities': 'truespeech; '}],
  },
  'Brenneri': {
    'description': 'This subtype is applied to brenneris and creatures related to brenneris. If the NPC is of the brenneri race (page 8, AA3), it also gains the favored object and hold breath racial traits',
    'trait': [],
    'reference': 'Alien Archive 3 pg. 148',
    'adjustment': [
      {'npcSenses': 'Darkvision 60 ft.; '},
      {'npcOtherAbilities': 'swim speed; '}],
    'masterSkills': ['npcSens', 'npcDipl'],
    'goodSkills': [],
  },
  'Cold': {
    'description': 'Creatures with this subtype are usually native to frigid environments.',
    'reference': ' Alien Archive pg. 134',
    'trait': [], 'adjustment': [
      {'npcImmunities': 'immunity to cold; '},
      {'npcWeaknesses': 'vulnerable to fire; '},
    ],
  },
  'Daemon': {
    'description': 'Daemons are fiends, or evil outsiders, native to Abaddon.',
    'reference': 'Alien Archive pg. 134',
    'trait': [],
    'adjustment': [
      {'npcResistances': 'resistance 10 to cold, electricity, and fire; '},
      {'npcImmunities': 'iImmunity to acid, death effects, disease, and poison; '},
      {'npcOtherAbilities': 'gains ability to summon allies; telepathy; '}],
  },
  'Damai': {
    'description': 'This subtype is applied to damais and creatures related to damais. if the NPC is of the damai race, it gains the scrappy racial trait and Stealth and Survival as master skills',
    'reference': 'Alien Archive 2 pg. 136',
    'trait': [],
    'adjustment': [
      {'npcSenses': 'Darkvision 60 ft.; '},
    ],
  },
  'Demon': {
    'description': 'Demons are fiends, or evil outsiders, native to the Abyss.',
    'reference': 'Alien Archive 2 pg. 136, Alien Archive pg. 134',
    'trait': [],
    'adjustment': [
      {'npcResistances': 'resistance 10 to acid, cold, and fire; '},
      {'npcImmunities': 'Immunity to electricity and poison; '},
      {'npcOtherAbilities': 'summon allies; telepathy 100 ft.; '}],
  },
  'Dessamar': {
    'description': 'This subtype is applied to dessamars and creatures related to dessamars.  If the NPC is of the dessamar race (Dessamar Imago or Dessamar Instar), it can use the following spells as spell-like abilities: 1/day—charm person; at will—detect magic and telepathic message. A dessamar imago has a land speed of 20 feet and an extraordinary fly speed of 20 feet with average maneuverability, as well as the fragile limbs and twinkle racial traits. A dessamar instar has a land speed of 30 feet and a climb speed of 30 feet, and a +2 racial bonus to KAC and saving throws against any effect that forces them to move or knocks them prone. An instar also has the dream dust and poor vision racial traits.',
    'reference': 'Source Alien Archive 3 pg. 148',
    'trait': [],
    'adjustment': [{'npcSenses': 'Blindsense (scent) 30 ft., low-light vision; '}],
  },
  'Devil': {
    'description': 'Devils are fiends, or evil outsiders, native to Hell.',
    'reference': 'Alien Archive 2 pg. 136, Alien Archive pg. 134',
    'trait': [],
    'specials': [
      {'npcSpecialsTemp': {'See in darkness;': 'The creature can see perfectly in darkness of any kind, including magical darkness.'}},
    ],
    'adjustment': [
      {'npcResistances': 'resistance 10 to acid and cold; '},
      {'npcImmunities': 'immunity to fire and poison; '},
      {'npcOtherAbilities': 'summon allies; telepathy 100 ft.; '},
      {'npcSenses': 'See in Darkness; '},
    ],
  },
  'Dirindi': {
    'description': 'This subtype is applied to dirindis and creatures related to dirindis. if the NPC is of the dirindi race, it also gains the electrical affinity racial trait and Diplomacy and Perception as master skills.',
    'reference': 'Alien Archive 3 pg. 148',
    'trait': [],
    'adjustment': [
      {'npcSenses': 'Blindsight (electricity) 60 ft., low-light vision; '},
    ],
  },
  'Dwarf': {
    'description': 'This subtype is applied to dwarves and creatures related to dwarves. if the NPC is of the dwarven race, it also gains the slow but steady, stonecunning, traditional enemies, and weapon familiarity racial traits.',
    'reference': 'Alien Archive pg. 134',
    'trait': [],
    'adjustment': [{'npcSenses': 'Darkvision 60 ft.; '}],
  },
  'Earth': {'description': '', 'reference': '', 'trait': [], 'adjustment': []},
  'Elemental': {
    'description': '',
    'reference': '',
    'trait': [],
    'adjustment': [],
  },
  'Elf': {'description': '', 'reference': '', 'trait': [], 'adjustment': []},
  'Espraksa': {
    'description': '',
    'reference': '',
    'trait': [],
    'adjustment': [],
  },
  'Extraplanar': {
    'description': '',
    'reference': '',
    'trait': [],
    'adjustment': [],
  },
  'Fire': {'description': '', 'reference': '', 'trait': [], 'adjustment': []},
  'Giant': {'description': '', 'reference': '', 'trait': [], 'adjustment': []},
  'Gnome': {'description': '', 'reference': '', 'trait': [], 'adjustment': []},
  'Goblinoid': {
    'description': '',
    'reference': '',
    'trait': [],
    'adjustment': [],
  },
  'Gray': {'description': '', 'reference': '', 'trait': [], 'adjustment': []},
  'Halfling': {
    'description': '',
    'reference': '',
    'trait': [],
    'adjustment': [],
  },
  'Human': {'description': '', 'reference': '', 'trait': [], 'adjustment': []},
  'Ikeshti': {
    'description': '',
    'reference': '',
    'trait': [],
    'adjustment': [],
  },
  'Incorporeal': {
    'description': '',
    'reference': '',
    'trait': [],
    'adjustment': [],
  },
  'Inevitable': {
    'description': '',
    'reference': '',
    'trait': [],
    'adjustment': [],
  },
  'Kami': {'description': '', 'reference': '', 'trait': [], 'adjustment': []},
  'Kasatha': {
    'description': '',
    'reference': '',
    'trait': [],
    'adjustment': [],
  },
  'Khizar': {'description': '', 'reference': '', 'trait': [], 'adjustment': []},
  'Lashunta': {
    'description': '',
    'reference': '',
    'trait': [],
    'adjustment': [],
  },
  'Maraquoi': {
    'description': '',
    'reference': '',
    'trait': [],
    'adjustment': [],
  },
  'Mindscape': {
    'description': '',
    'reference': '',
    'trait': [],
    'adjustment': [],
  },
  'Native': {'description': '', 'reference': '', 'trait': [], 'adjustment': []},
  'Oni': {'description': '', 'reference': '', 'trait': [], 'adjustment': []},
  'Orc': {'description': '', 'reference': '', 'trait': [], 'adjustment': []},
  'Pahtra': {'description': '', 'reference': '', 'trait': [], 'adjustment': []},
  'Phentomite': {
    'description': '',
    'reference': '',
    'trait': [],
    'adjustment': [],
  },
  'Plantlike': {
    'description': '',
    'reference': '',
    'trait': [],
    'adjustment': [],
  },
  'Protean': {
    'description': '',
    'reference': '',
    'trait': [],
    'adjustment': [],
  },
  'Pyric Revenant': {
    'description': '',
    'reference': '',
    'trait': [],
    'adjustment': [],
  },
  'Pyric Wraith': {
    'description': '',
    'reference': '',
    'trait': [],
    'adjustment': [],
  },
  'Reptoid': {
    'description': '',
    'reference': '',
    'trait': [],
    'adjustment': [],
  },
  'Reptoid Hybrid': {
    'description': '',
    'reference': '',
    'trait': [],
    'adjustment': [],
  },
  'Ryphorian': {
    'description': '',
    'reference': '',
    'trait': [],
    'adjustment': [],
  },
  'Sarcesian': {
    'description': '',
    'reference': '',
    'trait': [],
    'adjustment': [],
  },
  'Shakalta': {
    'description': '',
    'reference': '',
    'trait': [],
    'adjustment': [],
  },
  'Shapechanger': {
    'description': '',
    'reference': '',
    'trait': [],
    'adjustment': [],
  },
  'Shatori': {
    'description': '',
    'reference': '',
    'trait': [],
    'adjustment': [],
  },
  'Shimreen': {
    'description': '',
    'reference': '',
    'trait': [],
    'adjustment': [],
  },
  'Shirren': {
    'description': '',
    'reference': '',
    'trait': [],
    'adjustment': [],
  },
  'Skittermander': {
    'description': '',
    'reference': '',
    'trait': [],
    'adjustment': [],
  },
  'Spectra': {
    'description': '',
    'reference': '',
    'trait': [],
    'adjustment': [],
  },
  'Strix': {'description': '', 'reference': '', 'trait': [], 'adjustment': []},
  'Swarm': {'description': '', 'reference': '', 'trait': [], 'adjustment': []},
  'Troop': {'description': '', 'reference': '', 'trait': [], 'adjustment': []},
  'Velstrac': {
    'description': '',
    'reference': '',
    'trait': [],
    'adjustment': [],
  },
  'Verthani': {
    'description': '',
    'reference': '',
    'trait': [],
    'adjustment': [],
  },
  'Vesk': {'description': '', 'reference': '', 'trait': [], 'adjustment': []},
  'Vlaka': {'description': '', 'reference': '', 'trait': [], 'adjustment': []},
  'Water': {'description': '', 'reference': '', 'trait': [], 'adjustment': []},
  'Ysoki': {'description': '', 'reference': '', 'trait': [], 'adjustment': []},

  // Advanced Occult Guide
  'Anunnaki': {
    'description': '',
    'reference': '',
    'trait': [],
    'adjustment': [],
  },
  'Deoxyomorphic': {
    'description': '',
    'reference': '',
    'trait': [],
    'adjustment': [],
  },
  'Great Old One': {
    'description': '',
    'reference': '',
    'trait': [],
    'adjustment': [],
  },
  'Kitsune': {
    'description': '',
    'reference': '',
    'trait': [],
    'adjustment': [],
  },
  'Kumiho': {'description': '', 'reference': '', 'trait': [], 'adjustment': []},
  'Levialogos': {
    'description': '',
    'reference': '',
    'trait': [],
    'adjustment': [],
  },
  'Soulless': {
    'description': '',
    'reference': '',
    'trait': [],
    'adjustment': [],
  },
  'Soulshell': {
    'description': '',
    'reference': '',
    'trait': [],
    'adjustment': [],
  },
  'Uramae': {'description': '', 'reference': '', 'trait': [], 'adjustment': []},

};
