const npcSubTypes = {
  subtypes: [
    'Aeon',
    'Aquatic',
    'Azata',
    'Brenneri',
    'Cold',
    'Damai',
    'Demon',
    'Dessamar',
    'Devil',
    'Dirindi',
    'Earth',
    'Elemental',
    'Espraksa',
    'Extraplanar',
    'Fire',
    'Giant',
    'Goblinoid',
    'Incorporeal',
    'Kami',
    'Khizar',
    'Oni',
    'Orc',
    'Pahtra',
    'Phentomite',
    'Plantlike',
    'Pyric Revenant',
    'Pyric Wraith',
    'Shakalta',
    'Shapechanger',
    'Shatori',
    'Shimreen',
    'Skittermander',
    'Spectra',
    'Strix',
    'Swarm',
    'Velstrac',
    'Vlaka',
    'Water',

    'Anunnaki',
    'Deoxyomorphic',
    'Great Old One',
    'Kitsune',
    'Kumiho',
    'Levialogos',
    'Soulless',
    'Soulshell',
    'Uramae'],

  'Aeon': {'description' : 'Aeons are a race of neutral outsiders who maintain the balance of reality.',
    'trait': [], 'adjustment':[
      {'npcImmunities': 'Immunity to cold, critical hits, and poison;'}
    ] },
  'Aquatic': {'description' : '', 'trait': [], 'adjustment':[] },
  'Azata': {'description' : '', 'trait': [], 'adjustment':[] },
  'Brenneri': {'description' : '', 'trait': [], 'adjustment':[] },
  'Cold': {'description' : '', 'trait': [], 'adjustment':[] },
  'Damai': {'description' : '', 'trait': [], 'adjustment':[] },
  'Demon': {'description' : '', 'trait': [], 'adjustment':[] },
  'Dessamar': {'description' : '', 'trait': [], 'adjustment':[] },
  'Devil': {'description' : '', 'trait': [], 'adjustment':[] },
  'Dirindi': {'description' : '', 'trait': [], 'adjustment':[] },
  'Earth': {'description' : '', 'trait': [], 'adjustment':[] },
  'Elemental': {'description' : '', 'trait': [], 'adjustment':[] },
  'Espraksa': {'description' : '', 'trait': [], 'adjustment':[] },
  'Extraplanar': {'description' : '', 'trait': [], 'adjustment':[] },
  'Fire': {'description' : '', 'trait': [], 'adjustment':[] },
  'Giant': {'description' : '', 'trait': [], 'adjustment':[] },
  'Goblinoid': {'description' : '', 'trait': [], 'adjustment':[] },
  'Incorporeal': {'description' : '', 'trait': [], 'adjustment':[] },
  'Kami': {'description' : '', 'trait': [], 'adjustment':[] },
  'Khizar': {'description' : '', 'trait': [], 'adjustment':[] },
  'Oni': {'description' : '', 'trait': [], 'adjustment':[] },
  'Orc': {'description' : '', 'trait': [], 'adjustment':[] },
  'Pahtra': {'description' : '', 'trait': [], 'adjustment':[] },
  'Phentomite': {'description' : '', 'trait': [], 'adjustment':[] },
  'Plantlike': {'description' : '', 'trait': [], 'adjustment':[] },
  'Pyric Revenant': {'description' : '', 'trait': [], 'adjustment':[] },
  'Pyric Wraith': {'description' : '', 'trait': [], 'adjustment':[] },
  'Shakalta': {'description' : '', 'trait': [], 'adjustment':[] },
  'Shapechanger': {'description' : '', 'trait': [], 'adjustment':[] },
  'Shatori': {'description' : '', 'trait': [], 'adjustment':[] },
  'Shimreen': {'description' : '', 'trait': [], 'adjustment':[] },
  'Skittermander': {'description' : '', 'trait': [], 'adjustment':[] },
  'Spectra': {'description' : '', 'trait': [], 'adjustment':[] },
  'Strix': {'description' : '', 'trait': [], 'adjustment':[] },
  'Swarm': {'description' : '', 'trait': [], 'adjustment':[] },
  'Velstrac': {'description' : '', 'trait': [], 'adjustment':[] },
  'Vlaka': {'description' : '', 'trait': [], 'adjustment':[] },
  'Water': {'description' : '', 'trait': [], 'adjustment':[] },

  // Advanced Occult Guide
  'Anunnaki': {'description' : '', 'trait': [], 'adjustment':[] },
  'Deoxyomorphic': {'description' : '', 'trait': [], 'adjustment':[] },
  'Great Old One': {'description' : '', 'trait': [], 'adjustment':[] },
  'Kitsune': {'description' : '', 'trait': [], 'adjustment':[] },
  'Kumiho': {'description' : '', 'trait': [], 'adjustment':[] },
  'Levialogos': {'description' : '', 'trait': [], 'adjustment':[] },
  'Soulless': {'description' : '', 'trait': [], 'adjustment':[] },
  'Soulshell': {'description' : '', 'trait': [], 'adjustment':[] },
  'Uramae': {'description' : '', 'trait': [], 'adjustment':[] }
  
};
