const npcSubTypes = {
  subtypes: [
    'Aanung-an',
    'Aeon',
    'Agathion',
    'Air',
    'Android',
    'Angel',
    'Aquatic',
    'Archon',
    'Azata',
    'Brenneri',
    'Cold',
    'Daemon',
    'Damai',
    'Demon',
    'Dessamar',
    'Devil',
    'Dirindi',
    'Dwarf',
    'Earth',
    'Elemental',
    'Elf',
    'Espraksa',
    'Extraplanar',
    'Fire',
    'Giant',
    'Gnome',
    'Goblinoid',
    'Gray',
    'Halfling',
    'Human',
    'Ikeshti',
    'Incorporeal',
    'Inevitable',
    'Kami',
    'Kasatha',
    'Khizar',
    'Lashunta',
    'Maraquoi',
    'Mindscape',
    'Native',
    'Oni',
    'Orc',
    'Pahtra',
    'Phentomite',
    'Plantlike',
    'Protean',
    'Pyric Revenant',
    'Pyric Wraith',
    'Reptoid',
    'Reptoid Hybrid',
    'Ryphorian',
    'Sarcesian',
    'Shakalta',
    'Shapechanger',
    'Shatori',
    'Shimreen',
    'Shirren',
    'Skittermander',
    'Spectra',
    'Strix',
    'Swarm',
    'Troop',
    'Velstrac',
    'Verthani',
    'Vesk',
    'Vlaka',
    'Water',
    'Ysoki',

    'Anunnaki',
    'Deoxyomorphic',
    'Great Old One',
    'Kitsune',
    'Kumiho',
    'Levialogos',
    'Soulless',
    'Soulshell',
    'Uramae'],

  'Aeon': {
    'description': 'Aeons are a race of neutral outsiders who maintain the balance of reality.',
    'trait': [], 'adjustment': [
      {'npcImmunities': 'Immunity to cold, critical hits, and poison;'},
    ],
  },
  'Aanung-an': {'description': '', 'trait': [], 'adjustment': []},
  'Agathion': {'description': '', 'trait': [], 'adjustment': []},
  'Air': {'description': '', 'trait': [], 'adjustment': []},
  'Android': {'description': '', 'trait': [], 'adjustment': []},
  'Angel': {'description': '', 'trait': [], 'adjustment': []},
  'Aquatic': {'description': '', 'trait': [], 'adjustment': []},
  'Archon': {'description': '', 'trait': [], 'adjustment': []},
  'Azata': {'description': '', 'trait': [], 'adjustment': []},
  'Brenneri': {'description': '', 'trait': [], 'adjustment': []},
  'Cold': {'description': '', 'trait': [], 'adjustment': []},
  'Daemon': {'description': '', 'trait': [], 'adjustment': []},
  'Damai': {'description': '', 'trait': [], 'adjustment': []},
  'Demon': {'description': '', 'trait': [], 'adjustment': []},
  'Dessamar': {'description': '', 'trait': [], 'adjustment': []},
  'Devil': {'description': '', 'trait': [], 'adjustment': []},
  'Dirindi': {'description': '', 'trait': [], 'adjustment': []},
  'Dwarf': {'description': '', 'trait': [], 'adjustment': []},
  'Earth': {'description': '', 'trait': [], 'adjustment': []},
  'Elemental': {'description': '', 'trait': [], 'adjustment': []},
  'Elf': {'description': '', 'trait': [], 'adjustment': []},
  'Espraksa': {'description': '', 'trait': [], 'adjustment': []},
  'Extraplanar': {'description': '', 'trait': [], 'adjustment': []},
  'Fire': {'description': '', 'trait': [], 'adjustment': []},
  'Giant': {'description': '', 'trait': [], 'adjustment': []},
  'Gnome': {'description': '', 'trait': [], 'adjustment': []},
  'Goblinoid': {'description': '', 'trait': [], 'adjustment': []},
  'Gray': {'description': '', 'trait': [], 'adjustment': []},
  'Halfling': {'description': '', 'trait': [], 'adjustment': []},
  'Human': {'description': '', 'trait': [], 'adjustment': []},
  'Ikeshti': {'description': '', 'trait': [], 'adjustment': []},
  'Incorporeal': {'description': '', 'trait': [], 'adjustment': []},
  'Inevitable': {'description': '', 'trait': [], 'adjustment': []},
  'Kami': {'description': '', 'trait': [], 'adjustment': []},
  'Kasatha': {'description': '', 'trait': [], 'adjustment': []},
  'Khizar': {'description': '', 'trait': [], 'adjustment': []},
  'Lashunta': {'description': '', 'trait': [], 'adjustment': []},
  'Maraquoi': {'description': '', 'trait': [], 'adjustment': []},
  'Mindscape': {'description': '', 'trait': [], 'adjustment': []},
  'Native': {'description': '', 'trait': [], 'adjustment': []},
  'Oni': {'description': '', 'trait': [], 'adjustment': []},
  'Orc': {'description': '', 'trait': [], 'adjustment': []},
  'Pahtra': {'description': '', 'trait': [], 'adjustment': []},
  'Phentomite': {'description': '', 'trait': [], 'adjustment': []},
  'Plantlike': {'description': '', 'trait': [], 'adjustment': []},
  'Protean': {'description': '', 'trait': [], 'adjustment': []},
  'Pyric Revenant': {'description': '', 'trait': [], 'adjustment': []},
  'Pyric Wraith': {'description': '', 'trait': [], 'adjustment': []},
  'Reptoid': {'description': '', 'trait': [], 'adjustment': []},
  'Reptoid Hybrid': {'description': '', 'trait': [], 'adjustment': []},
  'Ryphorian': {'description': '', 'trait': [], 'adjustment': []},
  'Sarcesian': {'description': '', 'trait': [], 'adjustment': []},
  'Shakalta': {'description': '', 'trait': [], 'adjustment': []},
  'Shapechanger': {'description': '', 'trait': [], 'adjustment': []},
  'Shatori': {'description': '', 'trait': [], 'adjustment': []},
  'Shimreen': {'description': '', 'trait': [], 'adjustment': []},
  'Shirren': {'description': '', 'trait': [], 'adjustment': []},
  'Skittermander': {'description': '', 'trait': [], 'adjustment': []},
  'Spectra': {'description': '', 'trait': [], 'adjustment': []},
  'Strix': {'description': '', 'trait': [], 'adjustment': []},
  'Swarm': {'description': '', 'trait': [], 'adjustment': []},
  'Troop': {'description': '', 'trait': [], 'adjustment': []},
  'Velstrac': {'description': '', 'trait': [], 'adjustment': []},
  'Verthani': {'description': '', 'trait': [], 'adjustment': []},
  'Vesk': {'description': '', 'trait': [], 'adjustment': []},
  'Vlaka': {'description': '', 'trait': [], 'adjustment': []},
  'Water': {'description': '', 'trait': [], 'adjustment': []},
  'Ysoki': {'description': '', 'trait': [], 'adjustment': []},

  // Advanced Occult Guide
  'Anunnaki': {'description': '', 'trait': [], 'adjustment': []},
  'Deoxyomorphic': {'description': '', 'trait': [], 'adjustment': []},
  'Great Old One': {'description': '', 'trait': [], 'adjustment': []},
  'Kitsune': {'description': '', 'trait': [], 'adjustment': []},
  'Kumiho': {'description': '', 'trait': [], 'adjustment': []},
  'Levialogos': {'description': '', 'trait': [], 'adjustment': []},
  'Soulless': {'description': '', 'trait': [], 'adjustment': []},
  'Soulshell': {'description': '', 'trait': [], 'adjustment': []},
  'Uramae': {'description': '', 'trait': [], 'adjustment': []},

};
