var summoningGrafts = {
  grafts: [
    'Aeon',
    'Agathion',
    'Angel',
    'Archon',
    'Azata',
    'Daemon',
    'Demon',
    'Devil',
    'First World Beast',
    'Inevitable',
    'Protean',
    'Robot',
    'Shadow Creature',
  ],
  'Aeon': {'description': '', 'train': [], 'adjustment': []},
  'Agathion': {'description': '', 'train': [], 'adjustment': []},
  'Angel': {'description': '', 'train': [], 'adjustment': []},
  'Archon': {'description': '', 'train': [], 'adjustment': []},
  'Azata': {'description': '', 'train': [], 'adjustment': []},
  'Daemon': {'description': '', 'train': [], 'adjustment': []},
  'Demon': {'description': '', 'train': [], 'adjustment': []},
  'Devil': {'description': '', 'train': [], 'adjustment': []},
  'First World Beast': {'description': '', 'train': [], 'adjustment': []},
  'Inevitable': {'description': '', 'train': [], 'adjustment': []},
  'Protean': {'description': '', 'train': [], 'adjustment': []},
  'Robot': {'description': '', 'train': [], 'adjustment': []},
  'Shadow Creature': {'description': '', 'train': [], 'adjustment': []},
};